volumes:
  postgres-data:
    driver: local

services:

  reverse_proxy:
    container_name: "nginx"
    image: nginx:1.25.3-alpine-slim
    volumes:
      - ./site-content:/usr/share/nginx/html
      - ./conf/nginx-http.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks: 
      - abbaye11

networks:
  abbaye11:
    name: abbaye11

    