name: deploy-nginx
run-name: Deploy nginx-reverse-proxy with docker compose
on: [push]
jobs:
  git_pull_docker_compose:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Git pull and docker-compose deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 128.65.199.31
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: |
          cd /Users/seb/Docker/abbaye11.ch/nginx-reverse-proxy
          /usr/bin/git pull origin master
          /usr/local/bin/docker compose up -d
