name: ssh-remote-test
run-name: Deploy nginx-reverse-proxy with docker compose
on: [push]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: master
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: abbaye11.internet-box.ch
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: |
          docker compose up